export const allPresets = [
	/* Clients */
	{
		filename: "secret-clean",
		path: "/clouds/clients/secret-clean.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "mamypoko",
		path: "/clouds/clients/mamypoko.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "salezone",
		path: "/clouds/clients/salezone.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "advan",
		path: "/clouds/clients/advan.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "avaro",
		path: "/clouds/clients/avaro.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "manzone",
		path: "/clouds/clients/manzone.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "cakdoyok",
		path: "/clouds/clients/cakdoyok.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "herborist",
		path: "/clouds/clients/herborist.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "ace-fashion",
		path: "/clouds/clients/ace-fashion.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "tnt-beauty",
		path: "/clouds/clients/tnt-beauty.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "nuface",
		path: "/clouds/clients/nuface.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "cbd",
		path: "/clouds/clients/cbd.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "shenelin",
		path: "/clouds/clients/shenelin.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "mediclean",
		path: "/clouds/clients/mediclean.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "skintific",
		path: "/clouds/clients/skintific.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "neohaus",
		path: "/clouds/clients/neohaus.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "edwin",
		path: "/clouds/clients/edwin.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "goto",
		path: "/clouds/clients/goto.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "cryptoku",
		path: "/clouds/clients/cryptoku.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "sweaterpolosid",
		path: "/clouds/clients/sweaterpolosid.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "moc",
		path: "/clouds/clients/moc.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "miranda",
		path: "/clouds/clients/miranda.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "menstop",
		path: "/clouds/clients/menstop.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	{
		filename: "jadelux",
		path: "/clouds/clients/jadelux.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0086,
	},
	/* Services */
	{
		filename: "bisa-bikin-team-creative",
		path: "/clouds/services/bisa-bikin-team-creative.png",
		mimeType: "image/png",
		type: "image",
		size: 0.01763,
	},
	{
		filename: "bisa-bikin-famous-management",
		path: "/clouds/services/bisa-bikin-famous-management.png",
		mimeType: "image/png",
		type: "image",
		size: 0.02171,
	},
	{
		filename: "bisa-bikin-konten-creative",
		path: "/clouds/services/bisa-bikin-konten-creative.png",
		mimeType: "image/png",
		type: "image",
		size: 0.01707,
	},
	{
		filename: "bisa-bikin-marketing-digital",
		path: "/clouds/services/bisa-bikin-marketing-digital.png",
		mimeType: "image/png",
		type: "image",
		size: 0.0192,
	},
	{
		filename: "bisa-bikin-web",
		path: "/clouds/services/bisa-bikin-web.png",
		mimeType: "image/png",
		type: "image",
		size: 0.01917,
	},
	/* Service Items */
	{
		filename: "bbt-studio-serviceitems-1",
		path: "/clouds/serviceitems/bbt-studio/bbt-studio-serviceitems-1.png",
		mimeType: "image/png",
		type: "image",
		size: 1.15,
	},
	{
		filename: "bbt-studio-serviceitems-2",
		path: "/clouds/serviceitems/bbt-studio/bbt-studio-serviceitems-2.png",
		mimeType: "image/png",
		type: "image",
		size: 0.093474,
	},
	{
		filename: "bbt-studio-serviceitems-3",
		path: "/clouds/serviceitems/bbt-studio/bbt-studio-serviceitems-3.png",
		mimeType: "image/png",
		type: "image",
		size: 0.040098,
	},
	{
		filename: "bbf-serviceitems-1",
		path: "/clouds/serviceitems/bbf/bbf-serviceitems-1.png",
		mimeType: "image/png",
		type: "image",
		size: 0.078684,
	},
	{
		filename: "bbf-serviceitems-2",
		path: "/clouds/serviceitems/bbf/bbf-serviceitems-2.png",
		mimeType: "image/png",
		type: "image",
		size: 0.079145,
	},
	{
		filename: "bbf-serviceitems-3",
		path: "/clouds/serviceitems/bbf/bbf-serviceitems-3.png",
		mimeType: "image/png",
		type: "image",
		size: 1.01838,
	},
	{
		filename: "bbf-serviceitems-4",
		path: "/clouds/serviceitems/bbf/bbf-serviceitems-4.png",
		mimeType: "image/png",
		type: "image",
		size: 0.096578,
	},
	{
		filename: "bbk-serviceitems-1",
		path: "/clouds/serviceitems/bbk/bbk-serviceitems-1.png",
		mimeType: "image/png",
		type: "image",
		size: 0.069285,
	},
	{
		filename: "bbk-serviceitems-2",
		path: "/clouds/serviceitems/bbk/bbk-serviceitems-2.png",
		mimeType: "image/png",
		type: "image",
		size: 0.054914,
	},
	{
		filename: "bbm-serviceitems-1",
		path: "/clouds/serviceitems/bbm/bbm-serviceitems-1.png",
		mimeType: "image/png",
		type: "image",
		size: 0.054264,
	},
	{
		filename: "bbm-serviceitems-2",
		path: "/clouds/serviceitems/bbm/bbm-serviceitems-2.png",
		mimeType: "image/png",
		type: "image",
		size: 0.096935,
	},
	{
		filename: "bbm-serviceitems-3",
		path: "/clouds/serviceitems/bbm/bbm-serviceitems-3.png",
		mimeType: "image/png",
		type: "image",
		size: 0.056398,
	},
	{
		filename: "bbw-serviceitems-1",
		path: "/clouds/serviceitems/bbw/bbw-serviceitems-1.png",
		mimeType: "image/png",
		type: "image",
		size: 0.054906,
	},
	{
		filename: "bbw-serviceitems-2",
		path: "/clouds/serviceitems/bbw/bbw-serviceitems-2.png",
		mimeType: "image/png",
		type: "image",
		size: 0.077992,
	},
	{
		filename: "bbw-serviceitems-3",
		path: "/clouds/serviceitems/bbw/bbw-serviceitems-3.png",
		mimeType: "image/png",
		type: "image",
		size: 0.073056,
	},
	{
		filename: "bbw-serviceitems-4",
		path: "/clouds/serviceitems/bbw/bbw-serviceitems-4.png",
		mimeType: "image/png",
		type: "image",
		size: 0.081389,
	},
	/* Service Flag */
	{
		filename: "bug",
		path: "/clouds/flagicon/bug.png",
		mimeType: "image/png",
		type: "image",
		size: 0.00663,
	},
	{
		filename: "starPerson",
		path: "/clouds/flagicon/starPerson.png",
		mimeType: "image/png",
		type: "image",
		size: 0.00544,
	},
	{
		filename: "duck",
		path: "/clouds/flagicon/duck.png",
		mimeType: "image/png",
		type: "image",
		size: 0.00415,
	},
	{
		filename: "frog",
		path: "/clouds/flagicon/frog.png",
		mimeType: "image/png",
		type: "image",
		size: 0.00625,
	},
	{
		filename: "code",
		path: "/clouds/flagicon/code.png",
		mimeType: "image/png",
		type: "image",
		size: 0.00544,
	},
	/* Service Video */
	{
		filename: "bisa-bikin-team-creative",
		path: "/clouds/mov/bisa-bikin-team-creative.mp4",
		mimeType: "video/mp4",
		type: "video",
		size: 1.76,
	},
	{
		filename: "bisa-bikin-famous-mgmt",
		path: "/clouds/mov/bisa-bikin-famous-mgmt.mp4",
		mimeType: "video/mp4",
		type: "video",
		size: 0.32925,
	},
	{
		filename: "bisa-bikin-konten-creative",
		path: "/clouds/mov/bisa-bikin-konten-creative.mp4",
		mimeType: "video/mp4",
		type: "video",
		size: 0.11439,
	},
	{
		filename: "bisa-bikin-marketing-digital",
		path: "/clouds/mov/bisa-bikin-marketing-digital.mp4",
		mimeType: "video/mp4",
		type: "video",
		size: 0.95766,
	},
	{
		filename: "bisa-bikin-web",
		path: "/clouds/mov/bisa-bikin-web.mp4",
		mimeType: "video/mp4",
		type: "video",
		size: 0.46041,
	},
	{
		filename: "bbt-creative",
		path: "/clouds/mov/bbt-creative.mp4",
		mimeType: "video/mp4",
		type: "video",
		size: 0.34660,
	},
];